global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Новый job для проверки скорости интернета
  - job_name: 'speedtest'
    metrics_path: /metrics
    static_configs:
      - targets: ['speedtest-exporter:9469']
    scrape_interval: 10m
    scrape_timeout: 10m